[2018-08-16 23:02:59.553865] 'error'[2018-08-16 23:03:12.177389] 'error'[2018-08-16 23:03:26.305007] 'error'
[2018-08-16 23:03:47.204574] 'error'

[2018-08-16 23:04:03.557209] 'error'
[2018-08-16 23:10:31.172619] '200 OK'
[2018-08-16 23:16:16.903059] '200 OK'
[2018-08-16 23:18:23.962865] '503 NameError("name \'write_to_log\' is not defined",)'
[2018-08-16 23:18:35.149720] '503 NameError("name \'write_to_log\' is not defined",)'
[2018-08-16 23:18:37.714077] '503 NameError("name \'write_to_log\' is not defined",)'
[2018-08-16 23:18:39.136896] '503 NameError("name \'write_to_log\' is not defined",)'
[2018-08-16 23:18:52.466763] '503 NameError("name \'write_to_log\' is not defined",)'
[2018-08-16 23:19:03.290510] '503 NameError("name \'write_to_log\' is not defined",)'
[2018-08-16 23:19:18.314853] '503 NameError("name \'write_to_log\' is not defined",)'
[2018-08-16 23:19:31.298580] '503 NameError("name \'write_to_log\' is not defined",)'
[2018-08-16 23:19:53.093937] '503 NameError("name \'write_to_log\' is not defined",)'
[2018-08-16 23:25:04.212136] '503 NameError("name \'write_to_log\' is not defined",)'
[2018-08-17 11:40:37.898849] '503 NameError("name \'write_to_log\' is not defined",)'
[2018-08-17 11:59:53.178368] 'error'
[2018-08-17 12:00:13.756225] 'error'
[2018-08-17 12:01:00.389725] '503 NameError("name \'write_to_log\' is not defined",)'
[2018-08-17 12:01:06.015809] '503 NameError("name \'write_to_log\' is not defined",)'
[2018-08-17 12:01:29.080235] '503 NameError("name \'Utilities\' is not defined",)'
[2018-08-17 12:03:17.201870] '503 NameError("name \'Utilities\' is not defined",)'
[2018-08-17 12:04:26.087824] 'IntegrityError(\'(pymysql.err.IntegrityError) (1062, "Duplicate entry \\\'frike98@yahoo.com\\\' for key \\\'email\\\'")\',)'
[2018-08-17 12:04:26.088195] '200 OK'
[2018-08-17 12:04:46.941445] 'IntegrityError(\'(pymysql.err.IntegrityError) (1062, "Duplicate entry \\\'frike98@yahoo.com\\\' for key \\\'email\\\'")\',)'
[2018-08-17 12:04:46.941797] '200 OK'
[2018-08-17 12:07:40.854789] 'IntegrityError(\'(pymysql.err.IntegrityError) (1062, "Duplicate entry \\\'frike98@yahoo.com\\\' for key \\\'email\\\'")\',)'
[2018-08-17 12:07:40.855251] '503 (pymysql.err.IntegrityError) (1062, "Duplicate entry \'frike98@yahoo.com\' for key \'email\'") [SQL: \'INSERT INTO users (email, password, name, creation, last_login, session, picture) VALUES (%(email)s, %(password)s, %(name)s, %(creation)s, %(last_login)s, %(session)s, %(picture)s)\'] [parameters: {\'email\': \'frike98@yahoo.com\', \'password\': \'13601bda4ea78e55a07b98866d2be6be0744e3866f13c00c811cab608a28f322\', \'name\': \'Albert Ferencz\', \'creation\': None, \'last_login\': None, \'session\': None, \'picture\': None}] (Background on this error at: http://sqlalche.me/e/gkpj)'
[2018-08-17 12:07:40.855399] '503 TypeError("Object of type \'IntegrityError\' is not JSON serializable",)'
[2018-08-17 12:08:02.797302] 'IntegrityError(\'(pymysql.err.IntegrityError) (1062, "Duplicate entry \\\'frike98@yahoo.com\\\' for key \\\'email\\\'")\',)'
[2018-08-17 12:08:02.797733] '503 (pymysql.err.IntegrityError) (1062, "Duplicate entry \'frike98@yahoo.com\' for key \'email\'") [SQL: \'INSERT INTO users (email, password, name, creation, last_login, session, picture) VALUES (%(email)s, %(password)s, %(name)s, %(creation)s, %(last_login)s, %(session)s, %(picture)s)\'] [parameters: {\'email\': \'frike98@yahoo.com\', \'password\': \'13601bda4ea78e55a07b98866d2be6be0744e3866f13c00c811cab608a28f322\', \'name\': \'Albert Ferencz\', \'creation\': None, \'last_login\': None, \'session\': None, \'picture\': None}] (Background on this error at: http://sqlalche.me/e/gkpj)'
[2018-08-17 12:08:02.797849] '503 TypeError("Object of type \'IntegrityError\' is not JSON serializable",)'
[2018-08-17 12:08:12.056588] 'IntegrityError(\'(pymysql.err.IntegrityError) (1062, "Duplicate entry \\\'frike98@yahoo.com\\\' for key \\\'email\\\'")\',)'
[2018-08-17 12:08:12.057050] '503 (pymysql.err.IntegrityError) (1062, "Duplicate entry \'frike98@yahoo.com\' for key \'email\'") [SQL: \'INSERT INTO users (email, password, name, creation, last_login, session, picture) VALUES (%(email)s, %(password)s, %(name)s, %(creation)s, %(last_login)s, %(session)s, %(picture)s)\'] [parameters: {\'email\': \'frike98@yahoo.com\', \'password\': \'13601bda4ea78e55a07b98866d2be6be0744e3866f13c00c811cab608a28f322\', \'name\': \'Albert Ferencz\', \'creation\': None, \'last_login\': None, \'session\': None, \'picture\': None}] (Background on this error at: http://sqlalche.me/e/gkpj)'
[2018-08-17 12:08:12.057200] '503 TypeError("Object of type \'IntegrityError\' is not JSON serializable",)'
[2018-08-17 12:12:44.420499] 'IntegrityError(\'(pymysql.err.IntegrityError) (1062, "Duplicate entry \\\'frike98@yahoo.com\\\' for key \\\'email\\\'")\',)'
[2018-08-17 12:12:44.421068] '503 IntegrityError(\'(pymysql.err.IntegrityError) (1062, "Duplicate entry \\\'frike98@yahoo.com\\\' for key \\\'email\\\'")\',)'
[2018-08-17 12:14:40.044069] 'IntegrityError(\'(pymysql.err.IntegrityError) (1062, "Duplicate entry \\\'frike98@yahoo.com\\\' for key \\\'email\\\'")\',)'
[2018-08-17 12:14:40.044606] '502 IntegrityError(\'(pymysql.err.IntegrityError) (1062, "Duplicate entry \\\'frike98@yahoo.com\\\' for key \\\'email\\\'")\',)'
[2018-08-17 12:17:32.425789] IntegrityError('(pymysql.err.IntegrityError) (1062, "Duplicate entry \'frike98@yahoo.com\' for key \'email\'")',)
 in user_model.py on line 63